# Generated by Django 2.0.1 on 2018-02-01 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.CharField(max_length=1024, verbose_name='Answer')),
                ('ans_date', models.DateTimeField(auto_now_add=True, verbose_name='Answer Date')),
                ('updated_date', models.DateTimeField(blank=True, null=True, verbose_name='Updated Date')),
            ],
            options={
                'verbose_name_plural': 'Answers',
                'ordering': ['-ans_date'],
            },
        ),
        migrations.CreateModel(
            name='LikeDislike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('like', models.PositiveIntegerField(blank=True, null=True)),
                ('dislike', models.PositiveIntegerField(blank=True, null=True)),
                ('answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='que_ans_app.Answer')),
            ],
            options={
                'verbose_name_plural': 'Likes & Dislikes',
                'ordering': ['-like'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish_date', models.DateTimeField(auto_now_add=True, verbose_name='Published Date')),
                ('question_text', models.CharField(max_length=256, verbose_name='Question')),
                ('updated_date', models.DateTimeField(blank=True, null=True, verbose_name='Updated Date')),
            ],
            options={
                'verbose_name_plural': 'Questions',
                'ordering': ['-publish_date'],
            },
        ),
        migrations.AddField(
            model_name='likedislike',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='que_ans_app.Question'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='que_ans_app.Question'),
        ),
    ]
